Build & Doc: simplify install instructions
openai/universe pull request #130
Opened 2017-01-24 23:03 UTC by rht

This way, explicit support for more systems can be added incrementally.

> * We run Python 3.5 internally, so the Python 3.5 variants will be much more thoroughly performance tested. Please let us know if you see any issues on 2.7.

Note that the tests for python 2.7 can be readily added to the travis.yml.

For OSX, the supported version range should be made explicit (homebrew recommends at least 10.10).

2017-01-24 23:21 UTC, tlbtlbtlb commented on Makefile
> +	UNAME_S := $(shell uname -s)
Syntax error here.

2017-01-24 23:32 UTC, rht commented on Makefile
> +	UNAME_S := $(shell uname -s)
(right, sorry I realized that only after)

2017-01-25 00:10 UTC, tlbtlbtlb requested changes
People have reported installing universe following the instructions without issues on Linux Mint and RHEL. And with a little fiddling, on Windows/Bash and OSX with MacPorts. This seems to make it worse for them: `make deps` will silently do nothing.
At least, `make deps` should have else clauses that print the current instructions.

Also, our Travis flow is to create a container that runs Tox. I'd rather have the `make deps` run inside that. It should get the same results as running tox in the universe directory. See tox.ini there.

2017-01-25 01:06 UTC, rht commented
> People have reported installing universe following the instructions without issues on Linux Mint and RHEL. And with a little fiddling, on Windows/Bash and OSX with MacPorts. This seems to make it worse for them: make deps will silently do nothing. At least, make deps should have else clauses that print the current instructions.

Noted. I have added a more informative message.

- [ ] Except for OSX case where it still defaults to `brew`.
- [ ] `make deps` in tox

2017-01-25 07:51 UTC, rht commented
@tlbtlbtlb 

Update: `make deps` for 14.04 has been tested through travis. By extrapolation, 16.04 should be fine too. The Darwin part is untested, however.

Also, I just noticed that the test suite does run a Python 2.7 virtualenv (which is still not sufficient to detect any lingering performance regression).

2017-02-12 10:38 UTC, Baschdl commented
@rht Couldn't you use travis to test also 16.04 and Mac OS automatically?

2017-02-13 09:02 UTC, rht commented
@Baschdl that will certainly do but might be overkill to test-run an already dockerized env, but can be added in a test-commit to just to test whether the build script runs well in 16.04 and macOS.

2018-04-05 18:53 UTC, closed without merging